/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.OperacionMatriz;
import util.generarPDF;
import util.Matriz_Excel;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.MatrizFraccion;
import javax.swing.JButton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Jarlin Fonseca-1151758- Natalia Ortiz-1151770
 */
public class InterfazGUI extends javax.swing.JFrame {

    private MatrizFraccion matriz1;
    private MatrizFraccion matriz2;

    JFileChooser elegirBoton1 = new JFileChooser();

    /**
     * Creates new form interfaz
     */
    public InterfazGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarBoton(0);
        ocultarBoton(1);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/ufps.png"));
        return retValue;
    }

    public void imprimirAnuncio(String name) {
        
        JOptionPane.showMessageDialog(null, name);
    }
    
  

    public void mostrarBoton(int n) {
        if (n == 0) {
            jButtonDiagonalPrincipalA.setVisible(true);
            jButtonDiagonalPrincipalB.setVisible(true);

            jLabelSubtituloOperaciones.setVisible(true);
            jButtonSumarMatrices.setVisible(true);
            jButtonRestarMatrices.setVisible(true);
            jButtonMultiplicarMatrices.setVisible(true);
            jButtonSimplificarMatrizA.setVisible(true);
            jButtonSimplificarMatrizB.setVisible(true);
            jButtonMatrizTranspuestaA.setVisible(true);
            jButtonMatrizTranspuestaB.setVisible(true);
            jLabelImagenVista.setVisible(false);
            jLabelTituloA.setVisible(false);
            jLabelTituloB.setVisible(false);
            jLabelImagenMatrizA.setVisible(false);
            jLabelImagenMatrizB.setVisible(false);

        }
    }

    public void ocultarBoton(int n) {
        if (n == 1) {
            jButtonDiagonalPrincipalA.setVisible(false);
            jButtonDiagonalPrincipalB.setVisible(false);
            jLabelSubtituloOperaciones.setVisible(false);
            jButtonSumarMatrices.setVisible(false);
            jButtonRestarMatrices.setVisible(false);
            jButtonMultiplicarMatrices.setVisible(false);
            jButtonSimplificarMatrizA.setVisible(false);
            jButtonSimplificarMatrizB.setVisible(false);
            jButtonMatrizTranspuestaA.setVisible(false);
            jButtonMatrizTranspuestaB.setVisible(false);
            jLabelImagenVista.setVisible(true);
            jLabelTituloA.setVisible(true);
            jLabelTituloB.setVisible(true);
            jLabelImagenMatrizA.setVisible(true);
            jLabelImagenMatrizB.setVisible(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonFraccionMenorA = new javax.swing.JButton();
        jButtonFraccionMenorB = new javax.swing.JButton();
        jButtonMostrarMatrizA = new javax.swing.JButton();
        jButtonMostrarMatrizB = new javax.swing.JButton();
        jButtonDiagonalPrincipalA = new javax.swing.JButton();
        jButtonDiagonalPrincipalB = new javax.swing.JButton();
        jLabelSubtituloOperaciones = new javax.swing.JLabel();
        jButtonSumarMatrices = new javax.swing.JButton();
        jButtonRestarMatrices = new javax.swing.JButton();
        jButtonMultiplicarMatrices = new javax.swing.JButton();
        jButtonBorrarPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSimplificarMatrizA = new javax.swing.JButton();
        jButtonMatrizTranspuestaA = new javax.swing.JButton();
        jButtonSimplificarMatrizB = new javax.swing.JButton();
        jButtonMatrizTranspuestaB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelImagenMatrizA = new javax.swing.JLabel();
        jLabelTituloA = new javax.swing.JLabel();
        jLabelImagenMatrizB = new javax.swing.JLabel();
        jLabelTituloB = new javax.swing.JLabel();
        jLabelImagenVista = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 110, 50));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTitulo.setText("Calculadora de Matrices con Fracciones");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 201));
        jButton1.setText("Abrir Archivo Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 380, 60));

        jButtonFraccionMenorA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonFraccionMenorA.setForeground(new java.awt.Color(51, 51, 201));
        jButtonFraccionMenorA.setText("Fracción Menor de la Matriz A");
        jButtonFraccionMenorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFraccionMenorAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFraccionMenorA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 360, 50));

        jButtonFraccionMenorB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonFraccionMenorB.setForeground(new java.awt.Color(51, 51, 201));
        jButtonFraccionMenorB.setText("Fracción Menor de la Matriz B");
        jButtonFraccionMenorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFraccionMenorBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFraccionMenorB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 320, 50));

        jButtonMostrarMatrizA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMostrarMatrizA.setForeground(new java.awt.Color(51, 51, 201));
        jButtonMostrarMatrizA.setText("Mostrar Matriz A");
        jButtonMostrarMatrizA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarMatrizAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrarMatrizA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 360, 40));

        jButtonMostrarMatrizB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMostrarMatrizB.setForeground(new java.awt.Color(51, 52, 201));
        jButtonMostrarMatrizB.setText("Mostrar Matriz B");
        jButtonMostrarMatrizB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarMatrizBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrarMatrizB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 320, 40));

        jButtonDiagonalPrincipalA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonDiagonalPrincipalA.setForeground(new java.awt.Color(51, 51, 201));
        jButtonDiagonalPrincipalA.setText("Diagonal Principal de la Matriz A");
        jButtonDiagonalPrincipalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiagonalPrincipalAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiagonalPrincipalA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 360, 50));

        jButtonDiagonalPrincipalB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonDiagonalPrincipalB.setForeground(new java.awt.Color(51, 51, 201));
        jButtonDiagonalPrincipalB.setText("Diagonal Principal de la Matriz A");
        jButtonDiagonalPrincipalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiagonalPrincipalBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiagonalPrincipalB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 320, 50));

        jLabelSubtituloOperaciones.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelSubtituloOperaciones.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSubtituloOperaciones.setText("Operaciones de las Matrices A y B");
        getContentPane().add(jLabelSubtituloOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        jButtonSumarMatrices.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButtonSumarMatrices.setForeground(new java.awt.Color(51, 51, 201));
        jButtonSumarMatrices.setText("Sumar");
        jButtonSumarMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumarMatricesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSumarMatrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 160, 50));

        jButtonRestarMatrices.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButtonRestarMatrices.setForeground(new java.awt.Color(51, 51, 201));
        jButtonRestarMatrices.setText("Restar");
        jButtonRestarMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestarMatricesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRestarMatrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));

        jButtonMultiplicarMatrices.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButtonMultiplicarMatrices.setForeground(new java.awt.Color(51, 51, 201));
        jButtonMultiplicarMatrices.setText("Multiplicar");
        jButtonMultiplicarMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarMatricesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMultiplicarMatrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, -1, -1));

        jButtonBorrarPanel.setBackground(new java.awt.Color(255, 0, 0));
        jButtonBorrarPanel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonBorrarPanel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBorrarPanel.setText("Borrar Panel");
        jButtonBorrarPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarPanelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nota: Las matrices se muestren en PDF, por cuadro de diálogo  y en el panel del centro.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 20));

        jButtonSimplificarMatrizA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonSimplificarMatrizA.setForeground(new java.awt.Color(51, 51, 201));
        jButtonSimplificarMatrizA.setText("Simplificar Matriz A");
        jButtonSimplificarMatrizA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimplificarMatrizAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimplificarMatrizA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 360, 40));

        jButtonMatrizTranspuestaA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMatrizTranspuestaA.setForeground(new java.awt.Color(51, 51, 201));
        jButtonMatrizTranspuestaA.setText("Matriz Transpuesta De A");
        jButtonMatrizTranspuestaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatrizTranspuestaAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMatrizTranspuestaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 360, 40));

        jButtonSimplificarMatrizB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonSimplificarMatrizB.setForeground(new java.awt.Color(51, 51, 201));
        jButtonSimplificarMatrizB.setText("Simplificar Matriz B");
        jButtonSimplificarMatrizB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimplificarMatrizBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimplificarMatrizB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, 320, 40));

        jButtonMatrizTranspuestaB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMatrizTranspuestaB.setForeground(new java.awt.Color(51, 51, 201));
        jButtonMatrizTranspuestaB.setText("Matriz Transpuesta de B");
        jButtonMatrizTranspuestaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatrizTranspuestaBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMatrizTranspuestaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 320, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 400, 220));

        jLabelImagenMatrizA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Matriz.png"))); // NOI18N
        getContentPane().add(jLabelImagenMatrizA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jLabelTituloA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTituloA.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTituloA.setText("Matriz A de Fracciones");
        getContentPane().add(jLabelTituloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabelImagenMatrizB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Matriz.png"))); // NOI18N
        getContentPane().add(jLabelImagenMatrizB, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, -1, -1));

        jLabelTituloB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTituloB.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTituloB.setText("Matriz B de Fracciones");
        getContentPane().add(jLabelTituloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, -1, -1));

        jLabelImagenVista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tiposMatrices.png"))); // NOI18N
        getContentPane().add(jLabelImagenVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 560, -1));

        jLabelFondo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tecno.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 663));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed
    private void leerArchivoExcel() {
        try {
            if (elegirBoton1.showDialog(this, "ABRIR ARCHIVO/DOCUMENTO") == JFileChooser.APPROVE_OPTION) {
                if (elegirBoton1.getSelectedFile().canRead()) {
                    if (elegirBoton1.getSelectedFile().getName().endsWith("xls")) {
                        matriz1 = new MatrizFraccion(new Matriz_Excel(elegirBoton1.getSelectedFile().getAbsolutePath()).leerExcel(0));
                        matriz2 = new MatrizFraccion(new Matriz_Excel(elegirBoton1.getSelectedFile().getAbsolutePath()).leerExcel(1));
                        mostrarBoton(0);

                    } else {
                        imprimirAnuncio("El tipo de archivo debe ser .xls");
                        ocultarBoton(1);
                        leerArchivoExcel();
                    }
                }
            }

        } catch (Exception e) {
            Logger.getLogger(InterfazGUI.class.getName()).log(Level.SEVERE, null, e);
            imprimirAnuncio(e.getMessage());
         
            leerArchivoExcel();
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        leerArchivoExcel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonFraccionMenorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFraccionMenorBActionPerformed
        try {
            new generarPDF(matriz2.getMenor().toString(), "Menor Fracción de la Matriz B");
            imprimirAnuncio("La fracción menor de la matriz B es:\n" + matriz2.getMenor().toString());
            jTextArea1.setText("La fracción menor de la matriz B es:\n" + matriz2.getMenor().toString());
        } catch (Exception e) {
            imprimirAnuncio("Primero seleccione el archivo de Excel.xls donde tiene sus matrices");
        }
    }//GEN-LAST:event_jButtonFraccionMenorBActionPerformed

    private void jButtonDiagonalPrincipalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiagonalPrincipalAActionPerformed
        try {
            new generarPDF(matriz1.getDiagonalPrincipal().toString(), "Diagonal Principal de la Matriz A");
            imprimirAnuncio("La diagonal principal de la matriz A es:\n" + matriz1.getDiagonalPrincipal().toString());
            jTextArea1.setText("La diagonal principal de la matriz A es:\n" + matriz1.getDiagonalPrincipal().toString());
        } catch (Exception e) {

            imprimirAnuncio(e.getMessage());
        }
    }//GEN-LAST:event_jButtonDiagonalPrincipalAActionPerformed

    private void jButtonMostrarMatrizAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarMatrizAActionPerformed
   
        try {
            new generarPDF(matriz1.toString(), "Matriz A");
            imprimirAnuncio("La Matriz A es:\n" + matriz1.toString());
            jTextArea1.setText("La Matriz A es:\n" + matriz1.toString());
        } catch (Exception e) {
            imprimirAnuncio("Primero seleccione el archivo de Excel.xls donde tiene sus matrices");
            
        }
    }//GEN-LAST:event_jButtonMostrarMatrizAActionPerformed

    private void jButtonMostrarMatrizBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarMatrizBActionPerformed
        try {
            new generarPDF(matriz2.toString(), "Matriz B");
            imprimirAnuncio("La Matriz B es:\n" + matriz2.toString());
            jTextArea1.setText("La Matriz B es:\n" + matriz2.toString());
        } catch (Exception e) {
            imprimirAnuncio("Primero seleccione el archivo de Excel.xls donde tiene sus matrices");
           

        }
    }//GEN-LAST:event_jButtonMostrarMatrizBActionPerformed

    private void jButtonFraccionMenorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFraccionMenorAActionPerformed
        try {
            new generarPDF(matriz1.getMenor().toString(), "Menor Fracción de la Matriz A");

            imprimirAnuncio("La fracción menor de la matriz A es:\n" + matriz1.getMenor().toString());
            jTextArea1.setText("La fracción menor de la matriz A es:\n" + matriz1.getMenor().toString());
        } catch (Exception e) {
            imprimirAnuncio("Primero seleccione el archivo de Excel.xls donde tiene sus matrices");
        }

    }//GEN-LAST:event_jButtonFraccionMenorAActionPerformed

    private void jButtonDiagonalPrincipalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiagonalPrincipalBActionPerformed
        try {
            new generarPDF(matriz2.getDiagonalPrincipal().toString(), "Diagonal Principal de la Matriz B");
            imprimirAnuncio("La diagonal principal de la matriz B es:\n" + matriz2.getDiagonalPrincipal().toString());
            jTextArea1.setText("La diagonal principal de la matriz B es:\n" + matriz2.getDiagonalPrincipal().toString());
        } catch (Exception e) {

            imprimirAnuncio(e.getMessage());
        }
    }//GEN-LAST:event_jButtonDiagonalPrincipalBActionPerformed

    private void jButtonSumarMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumarMatricesActionPerformed
       
        try {
            String matriz = matriz1.getSumar(matriz2).toString();
            new generarPDF(matriz, "Suma de la Matriz A y B");
            imprimirAnuncio("Suma de la Matriz A y B:\n" + matriz);
            jTextArea1.setText("Suma de la Matriz A y B:\n" + matriz);
        } catch (Exception e) {
            imprimirAnuncio(e.getMessage());
        }
    }//GEN-LAST:event_jButtonSumarMatricesActionPerformed
 
    private void jButtonRestarMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestarMatricesActionPerformed
        try {
            new generarPDF(matriz1.getRestar(matriz2).toString(), "Resta de la Matriz A y B");
            imprimirAnuncio("Resta de la Matriz A y B:\n" + matriz1.getRestar(matriz2).toString());
            jTextArea1.setText("Resta de la Matriz A y B:\n" + matriz1.getRestar(matriz2).toString());
        } catch (Exception e) {
            imprimirAnuncio(e.getMessage());

        }
    }//GEN-LAST:event_jButtonRestarMatricesActionPerformed

    private void jButtonMultiplicarMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarMatricesActionPerformed
         try {
        new generarPDF(matriz1.getMultiplicación(matriz2).toString(), "Multiplicación de la Matriz A y B");
        imprimirAnuncio("Multiplicación de la Matriz A y B:\n" + matriz1.getMultiplicación(matriz2).toString());
        jTextArea1.setText("Multiplicación de la Matriz A y B:\n" + matriz1.getMultiplicación(matriz2).toString());
        } catch (Exception e) {
            imprimirAnuncio(e.getMessage());

        }
    }//GEN-LAST:event_jButtonMultiplicarMatricesActionPerformed

    private void jButtonBorrarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarPanelActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_jButtonBorrarPanelActionPerformed

    private void jButtonSimplificarMatrizAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimplificarMatrizAActionPerformed
        try {
            new generarPDF(matriz1.getMatrizSimplificada().toString(), "Matriz A Simplificada");

            imprimirAnuncio("Matriz A Simplificada:\n" + matriz1.getMatrizSimplificada().toString());
            jTextArea1.setText("Matriz A Simplificada:\n" + matriz1.getMatrizSimplificada().toString());
        } catch (Exception e) {
            imprimirAnuncio("Primero seleccione el archivo de Excel.xls donde tiene sus matrices");
        }
    }//GEN-LAST:event_jButtonSimplificarMatrizAActionPerformed

    private void jButtonMatrizTranspuestaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatrizTranspuestaAActionPerformed
        try {
            new generarPDF(matriz1.getTranspuesta().toString(), "Matriz Transpuesta de A");

            imprimirAnuncio("Matriz Transpuesta de A:\n" + matriz1.getTranspuesta().toString());
            jTextArea1.setText("Matriz Transpuesta de A:\n" + matriz1.getTranspuesta().toString());
        } catch (Exception e) {
            imprimirAnuncio(e.getMessage());
        }
    }//GEN-LAST:event_jButtonMatrizTranspuestaAActionPerformed

    private void jButtonSimplificarMatrizBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimplificarMatrizBActionPerformed
        try {
            new generarPDF(matriz1.getMatrizSimplificada().toString(), "Matriz B Simplificada");

            imprimirAnuncio("Matriz B Simplificada:\n" + matriz2.getMatrizSimplificada().toString());
            jTextArea1.setText("Matriz B Simplificada:\n" + matriz2.getMatrizSimplificada().toString());
        } catch (Exception e) {
            imprimirAnuncio("Primero seleccione el archivo de Excel.xls donde tiene sus matrices");
        }
    }//GEN-LAST:event_jButtonSimplificarMatrizBActionPerformed

    private void jButtonMatrizTranspuestaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatrizTranspuestaBActionPerformed
        try {
            new generarPDF(matriz2.getTranspuesta().toString(), "Matriz Transpuesta de B");

            imprimirAnuncio("Matriz Transpuesta de B:\n" + matriz2.getTranspuesta().toString());
            jTextArea1.setText("Matriz Transpuesta de B:\n" + matriz2.getTranspuesta().toString());
        } catch (Exception e) {
            imprimirAnuncio(e.getMessage());
        }
    }//GEN-LAST:event_jButtonMatrizTranspuestaBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBorrarPanel;
    private javax.swing.JButton jButtonDiagonalPrincipalA;
    private javax.swing.JButton jButtonDiagonalPrincipalB;
    private javax.swing.JButton jButtonFraccionMenorA;
    private javax.swing.JButton jButtonFraccionMenorB;
    private javax.swing.JButton jButtonMatrizTranspuestaA;
    private javax.swing.JButton jButtonMatrizTranspuestaB;
    private javax.swing.JButton jButtonMostrarMatrizA;
    private javax.swing.JButton jButtonMostrarMatrizB;
    private javax.swing.JButton jButtonMultiplicarMatrices;
    private javax.swing.JButton jButtonRestarMatrices;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSimplificarMatrizA;
    private javax.swing.JButton jButtonSimplificarMatrizB;
    private javax.swing.JButton jButtonSumarMatrices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImagenMatrizA;
    private javax.swing.JLabel jLabelImagenMatrizB;
    private javax.swing.JLabel jLabelImagenVista;
    private javax.swing.JLabel jLabelSubtituloOperaciones;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloA;
    private javax.swing.JLabel jLabelTituloB;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
